"""create exposure_signals table

Revision ID: cf49ba75dd0b
Revises: d67fee2f8f1f
Create Date: 2026-08-05 13:00:58.076729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf49ba75dd0b"
down_revision: Union[str, None] = "d67fee2f8f1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
