"""create assets, hosts, users tables

Revision ID: d67fee2f8f1f
Revises: 
Create Date: 2026-08-04 09:36:35.250797

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d67fee2f8f1f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.Column("discovery_source", sa.String(length=20), nullable=False),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_category"), "assets", ["category"], unique=False)
    op.create_index(op.f("ix_assets_identifier"), "assets", ["identifier"], unique=False)
    op.create_index(op.f("ix_assets_is_critical"), "assets", ["is_critical"], unique=False)
    op.create_index(op.f("ix_assets_last_seen"), "assets", ["last_seen"], unique=False)
    op.create_table(
        "hosts",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("operating_system", sa.String(length=100), nullable=True),
        sa.Column("is_internet_facing", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_index(
        op.f("ix_hosts_is_internet_facing"), "hosts", ["is_internet_facing"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("is_privileged", sa.Boolean(), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_index(op.f("ix_users_is_privileged"), "users", ["is_privileged"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_privileged"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_hosts_is_internet_facing"), table_name="hosts")
    op.drop_table("hosts")
    op.drop_index(op.f("ix_assets_last_seen"), table_name="assets")
    op.drop_index(op.f("ix_assets_is_critical"), table_name="assets")
    op.drop_index(op.f("ix_assets_identifier"), table_name="assets")
    op.drop_index(op.f("ix_assets_category"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
